server:
    port: 80
    servlet:
        context-path: /Shopme
spring:
    main:
        allow-circular-references: true
    datasource:
        password: password
        url: jdbc:mysql://localhost:3306/shopmedb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
                format_sql: true
        show-sql: false

    security:
        oauth2:
          client:
              registration:
                  google:
                      client-id: 992914229712-jc1ul4ebjvpvjs4dl41c6kditnke8gsh.apps.googleusercontent.com
                      client-secret: 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
                      scope:
                      - email
                      - profile
                  facebook:
                      client-id: 101627836188048
                      client-secret: efda2f84d74de579c969d0ccfbb89b0a
                      scope:
                      - email
                      - public_profile